In [3]:
# Random sampling
import torch
import numpy as np
torch.manual_seed(123)  # 设置随机数生成的种子,确保在相同种子的情况下能够复现相同的随机数序列。
random_tensor = torch.rand(3, 3)
print("Random tensor:")
print(random_tensor)

Random tensor:
tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665],
        [0.1366, 0.1025, 0.1841]])


### Reduction Ops

In [4]:
# argmax, argmin
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
max_indices = torch.argmax(x)  # 找到整个张量中最大值的索引
print(max_indices)
min_indices = torch.argmin(x)  # 找到整个张量中最小值的索引
print(min_indices)

tensor(5)
tensor(0)


In [5]:
# amax,amin在指定维度上找到最大值和最小值
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
max_values = torch.amax(x, dim=1)  # 在第1维度上找到每行的最大值
print(max_values)
min_values = torch.amin(x, dim=1)  # 在第1维度上找到每行的最小值
print(min_values)

tensor([3, 6])
tensor([1, 4])
