## Ndarray 对象
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)


| 参数   | 描述                           |
|--------|--------------------------------|
| object | 数组或嵌套的数列                 |
| dtype  | 数组元素的数据类型，可选         |
| copy   | 对象是否需要复制，可选           |
| order  | 创建数组的样式，C为行方向，F为列方向，A为任意方向（默认） |
| subok  | 默认返回一个与基类类型一致的数组 |
| ndmin  | 指定生成数组的最小维度           |

In [2]:
import numpy as np 
a = np.array([1,2,3])  
b = np.array([[1,  2],  [3,  4]])  
c = np.array([1, 2, 3, 4, 5], ndmin =  2) 
d = np.array([1,  2,  3], dtype = complex)  
a, b, c, d

(array([1, 2, 3]),
 array([[1, 2],
        [3, 4]]),
 array([[1, 2, 3, 4, 5]]),
 array([1.+0.j, 2.+0.j, 3.+0.j]))

## NumPy 数据类型
数据类型对象（numpy.dtype 类的实例）用来描述与数组对应的内存区域是如何使用，它描述了数据的以下几个方面：：

• 数据的类型（整数、浮点数或Python对象）
• 数据的大小（例如，整数使用多少个字节存储）
• 数据的字节顺序（小端法或大端法）
• 在结构化类型的情况下，字段的名称、每个字段的数据类型和每个字段所占的内存块的部分
• 如果数据类型是子数组，那么它的形状和数据类型是什么。

dtype 对象是使用以下语法构造的：

numpy.dtype(object, align, copy)

In [3]:
# 使用标量类型
dt = np.dtype(np.int32)
# int8, int16, int32, int64 四种数据类型可以使用字符串 'i1', 'i2','i4','i8' 代替
dt2 = np.dtype('i4')
# 字节顺序标注
dt3 = np.dtype('<i4')
# 创建结构化数据类型
dt4 = np.dtype([('name', np.str_, 20), ('age', np.int32), ('weight', np.float64)])
# 创建结构化数组
data = np.array([('John', 25, 68.5), ('Emily', 30, 55.2)], dtype=dt4)
dt, dt2, dt3, dt4, data, data['name']

(dtype('int32'),
 dtype('int32'),
 dtype('int32'),
 dtype([('name', '<U20'), ('age', '<i4'), ('weight', '<f8')]),
 array([('John', 25, 68.5), ('Emily', 30, 55.2)],
       dtype=[('name', '<U20'), ('age', '<i4'), ('weight', '<f8')]),
 array(['John', 'Emily'], dtype='<U20'))

## NumPy 数组属性
属性             | 说明
---------------|--------------------------
ndarray.ndim   | 秩，即轴的数量或维度的数量
ndarray.shape  | 数组的维度，对于矩阵，n行m列
ndarray.size   | 数组元素的总个数，相当于.shape中n\*m的值
ndarray.dtype  | ndarray对象的元素类型
ndarray.itemsize | ndarray对象中每个元素的大小，以字节为单位
ndarray.flags  | ndarray对象的内存信息
ndarray.real   | ndarray元素的实部
ndarray.imag   | ndarray元素的虚部
ndarray.data   | 包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性。
ndarray.T | 对数组进行转置

In [4]:
# ndarray.ndim 用于返回数组的维数
a = np.arange(24)  
print (a.ndim)             # a 现只有一个维度
# 现在调整其大小
b = a.reshape(2,4,3)  # b 现在拥有三个维度
print (b.ndim)

1
3


In [5]:
# ndarray.shape 返回数组维度
a = np.array([[1,2,3],[4,5,6]])  
print (a.shape)

(2, 3)


In [6]:
# reshape 返回指定shape的新数组
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2)  
print (b)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
# ndarray.itemsize 以字节的形式返回数组中每一个元素的大小。
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print (x.itemsize)
 
# 数组的 dtype 现在为 float64（八个字节） 
y = np.array([1,2,3,4,5], dtype = np.float64)  
print (y.itemsize)

1
8


In [8]:
# ndarray.flags 返回 ndarray 对象的内存信息
x = np.array([1,2,3,4,5])  
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

