## 转置矩阵

In [1]:
import numpy as np
 
a = np.arange(12).reshape(3,4)
 
print ('原数组：')
print (a)
print ('\n')
 
print ('转置数组：')
print (a.T)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## matlib.empty()
matlib.empty() 函数返回一个新的矩阵，语法格式为：

numpy.matlib.empty(shape, dtype, order)
参数说明：

shape: 定义新矩阵形状的整数或整数元组

Dtype: 可选，数据类型

order: C（行序优先） 或者 F（列序优先）

In [2]:
import numpy.matlib 
import numpy as np
 
print (np.matlib.empty((2,2)))
# 填充为随机数据

[[2.12199579e-314 9.78240060e-312]
 [4.20943930e-321 9.78240060e-312]]
